//we use hetera files so we can use there functions;
#include<stdio.h>
#include<stdlib.h>
#include<time.h>

int main()
{
    int number, guess, n=1; 
    srand(time(0));
    // number = rand();                          //using this we had no range of generating random number;
    number = rand()%100 + 1;                    //this generates random number ONLY bretween 1 to 100.
    // printf("The number is %d\n", number);  //This is necessary so the the number generated by the computer is hiddn.
    printf("WELCOME TO THE GAME!\n");
    
    do
    {
        printf("Guess the number between 1 to 100\n");
        scanf("%d", &guess);

        if (guess>number)
        {
            printf("Lower no. please\n");

        }
        else if (guess<number)
        {
            printf("Higher no. please\n");
        }
        else{
            printf("It took you %d number of guesses\n", n);
        }
        n++;
    } while (guess!=number);
    return 0;
}


//here we used do while loop , because i had to run the loop atleast once 
